apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexus-soc
resources:
  - namespace.yaml
  - soc-runtime-plan-configmap.yaml
  - soc-runtime.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: suricata-config
    files:
      - suricata.yaml=suricata.yaml
generatorOptions:
  disableNameSuffixHash: true
