apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wazuh-dashboard-ingress
spec:
  podSelector:
    matchLabels:
      app: wazuh-dashboard
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 5601
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wazuh-manager-ingress
spec:
  podSelector:
    matchLabels:
      app: wazuh-manager
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: UDP
          port: 1514
        - protocol: TCP
          port: 1515
        - protocol: TCP
          port: 55000
