apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
secretGenerator:
  - name: wazuh-auth
    literals:
      - indexer-username=admin
      - indexer-password=admin
      - dashboard-username=admin
      - dashboard-password=admin
generatorOptions:
  disableNameSuffixHash: true
